version: '3'

services:

  frontend:
    build: 
      context: ./../frontend
      dockerfile: ./../frontend/frontend.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - BROKER_URL=http://backend
  
  broker-service:
    build: 
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
  
  quote-service:
    build: 
      context: ./../quote-service
      dockerfile: ./../quote-service/quote-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      
  nginx:
    image: 'nginx:1.21.3-alpine'
    ports:
      - "80:80"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf